import { MapRecord } from '@/types/map-record';

export const SAMPLE_MAP_RECORDS: MapRecord[] = [
  // Synagogues
  {
    id: 'synagogue_1',
    layer_type: 'synagogue',
    name: 'Beth Shalom Congregation',
    city: 'New York',
    state_province: 'NY',
    country: 'USA',
    latitude: 40.7589,
    longitude: -73.9851,
    affiliation: 'Conservative',
    notes: 'Sample data — connect Google Sheets to load live records.',
  },
  {
    id: 'synagogue_2',
    layer_type: 'synagogue',
    name: 'Temple Emanuel',
    city: 'Beverly Hills',
    state_province: 'CA',
    country: 'USA',
    latitude: 34.0736,
    longitude: -118.4004,
    affiliation: 'Reform',
  },
  {
    id: 'synagogue_3',
    layer_type: 'synagogue',
    name: 'Kehilath Israel',
    city: 'Chicago',
    state_province: 'IL',
    country: 'USA',
    latitude: 41.8827,
    longitude: -87.6233,
    affiliation: 'Orthodox',
  },
  // Day Schools
  {
    id: 'school_1',
    layer_type: 'day_school',
    name: 'Hillel Day School',
    city: 'Pittsburgh',
    state_province: 'PA',
    country: 'USA',
    latitude: 40.4406,
    longitude: -79.9959,
    affiliation: 'Community',
  },
  {
    id: 'school_2',
    layer_type: 'day_school',
    name: 'Torah Academy of Minneapolis',
    city: 'Minneapolis',
    state_province: 'MN',
    country: 'USA',
    latitude: 44.9778,
    longitude: -93.2650,
    affiliation: 'Orthodox',
  },
  // Head Shluchim
  {
    id: 'shliach_1',
    layer_type: 'head_shliach',
    name: 'Rabbi Levi Greenberg',
    city: 'El Paso',
    state_province: 'TX',
    country: 'USA',
    latitude: 31.7619,
    longitude: -106.4850,
    email: 'rabbi@chabad-elpaso.com',
    whatsapp: '+1-915-555-0100',
  },
  {
    id: 'shliach_2',
    layer_type: 'head_shliach',
    name: 'Rabbi Mendel Liberow',
    city: 'Denver',
    state_province: 'CO',
    country: 'USA',
    latitude: 39.7392,
    longitude: -104.9903,
  },
  // Population
  {
    id: 'population_new_york_ny',
    layer_type: 'population',
    name: 'New York Jewish Population',
    city: 'New York',
    state_province: 'NY',
    country: 'USA',
    latitude: 40.7128,
    longitude: -74.0060,
    population: 1100000,
  },
  {
    id: 'population_los_angeles_ca',
    layer_type: 'population',
    name: 'Los Angeles Jewish Population',
    city: 'Los Angeles',
    state_province: 'CA',
    country: 'USA',
    latitude: 34.0522,
    longitude: -118.2437,
    population: 519200,
  },
  {
    id: 'population_chicago_il',
    layer_type: 'population',
    name: 'Chicago Jewish Population',
    city: 'Chicago',
    state_province: 'IL',
    country: 'USA',
    latitude: 41.8781,
    longitude: -87.6298,
    population: 291800,
  },
];
