import { Institution } from '@/types/institution';

export const SAMPLE_INSTITUTIONS: Institution[] = [
  {
    id: 1,
    name: 'Beth Shalom Synagogue',
    type: 'Synagogue',
    city: 'New York',
    state_province: 'NY',
    country: 'USA',
    latitude: 40.7589,
    longitude: -73.9851,
    website_url: 'https://example.com/bethshalom',
    facebook_url: null,
    youtube_url: null,
    education_activity: 'yes',
    activity_level: 'high',
    opportunity_score: 7,
    status: 'Active',
    next_action: 'Schedule Zoom call',
    notes: 'Very active Hebrew school. Open to curriculum collaboration.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Chabad of Los Angeles',
    type: 'Chabad',
    city: 'Los Angeles',
    state_province: 'CA',
    country: 'USA',
    latitude: 34.0522,
    longitude: -118.2437,
    website_url: 'https://example.com/chabadla',
    facebook_url: 'https://facebook.com/example',
    youtube_url: null,
    education_activity: 'yes',
    activity_level: 'high',
    opportunity_score: 8,
    status: 'Follow Up',
    next_action: 'Send program materials',
    notes: 'Runs weekly JLI classes. Strong online presence.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 3,
    name: 'Hillel Day School',
    type: 'School',
    city: 'Chicago',
    state_province: 'IL',
    country: 'USA',
    latitude: 41.8781,
    longitude: -87.6298,
    website_url: null,
    facebook_url: null,
    youtube_url: null,
    education_activity: 'yes',
    activity_level: 'medium',
    opportunity_score: 6,
    status: 'Needs Action',
    next_action: 'Follow up on curriculum inquiry',
    notes: 'K-8 day school. Curriculum director expressed interest.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'JCC of Greater Miami',
    type: 'JCC',
    city: 'Miami',
    state_province: 'FL',
    country: 'USA',
    latitude: 25.7617,
    longitude: -80.1918,
    website_url: 'https://example.com/jccmiami',
    facebook_url: null,
    youtube_url: 'https://youtube.com/example',
    education_activity: 'no',
    activity_level: 'low',
    opportunity_score: 5,
    status: 'Prospect',
    next_action: 'Initial outreach call',
    notes: 'Large membership. No current educational programming noted.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'Temple Emanu-El San Francisco',
    type: 'Synagogue',
    city: 'San Francisco',
    state_province: 'CA',
    country: 'USA',
    latitude: 37.7749,
    longitude: -122.4194,
    website_url: 'https://example.com/templeemanu',
    facebook_url: null,
    youtube_url: null,
    education_activity: 'yes',
    activity_level: 'high',
    opportunity_score: 9,
    status: 'Active',
    next_action: null,
    notes: 'Partner in Bay Area Jewish education network.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 6,
    name: 'Chabad of Boston',
    type: 'Chabad',
    city: 'Boston',
    state_province: 'MA',
    country: 'USA',
    latitude: 42.3601,
    longitude: -71.0589,
    website_url: 'https://example.com/chabadboston',
    facebook_url: 'https://facebook.com/chabadboston',
    youtube_url: null,
    education_activity: 'unknown',
    activity_level: 'medium',
    opportunity_score: 4,
    status: 'Follow Up',
    next_action: 'Confirm education programming details',
    notes: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 7,
    name: 'Torah Academy of Houston',
    type: 'School',
    city: 'Houston',
    state_province: 'TX',
    country: 'USA',
    latitude: 29.7604,
    longitude: -95.3698,
    website_url: null,
    facebook_url: null,
    youtube_url: null,
    education_activity: 'yes',
    activity_level: 'high',
    opportunity_score: 7,
    status: 'Needs Action',
    next_action: 'Schedule curriculum review',
    notes: 'Growing school. Interested in supplementary materials.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 8,
    name: 'Jewish Community Alliance Denver',
    type: 'JCC',
    city: 'Denver',
    state_province: 'CO',
    country: 'USA',
    latitude: 39.7392,
    longitude: -104.9903,
    website_url: 'https://example.com/jcadenver',
    facebook_url: null,
    youtube_url: null,
    education_activity: 'unknown',
    activity_level: 'none',
    opportunity_score: 3,
    status: 'Inactive',
    next_action: null,
    notes: 'Programming paused. Checking back in Q3.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 9,
    name: 'Seattle Jewish Education Gap',
    type: 'Opportunity',
    city: 'Seattle',
    state_province: 'WA',
    country: 'USA',
    latitude: 47.6062,
    longitude: -122.3321,
    website_url: null,
    facebook_url: null,
    youtube_url: null,
    education_activity: 'no',
    activity_level: 'none',
    opportunity_score: 6,
    status: 'Prospect',
    next_action: 'Research leadership contacts',
    notes: 'Gap identified: no education programming despite large Jewish population.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 10,
    name: 'Beit Midrash of Atlanta',
    type: 'Synagogue',
    city: 'Atlanta',
    state_province: 'GA',
    country: 'USA',
    latitude: 33.7490,
    longitude: -84.3880,
    website_url: 'https://example.com/beitmidrash',
    facebook_url: 'https://facebook.com/beitmidrash',
    youtube_url: 'https://youtube.com/beitmidrash',
    education_activity: 'yes',
    activity_level: 'medium',
    opportunity_score: 5,
    status: 'Active',
    next_action: 'Propose adult education series',
    notes: 'Strong adult learning culture. Very receptive leadership.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 11,
    name: 'Chabad of Tel Aviv Center',
    type: 'Chabad',
    city: 'Tel Aviv',
    state_province: 'Tel Aviv District',
    country: 'Israel',
    latitude: 32.0853,
    longitude: 34.7818,
    website_url: null,
    facebook_url: null,
    youtube_url: null,
    education_activity: 'yes',
    activity_level: 'high',
    opportunity_score: 8,
    status: 'Active',
    next_action: null,
    notes: 'International contact. Very active youth education.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 12,
    name: 'London Jewish Cultural Centre',
    type: 'JCC',
    city: 'London',
    state_province: 'England',
    country: 'UK',
    latitude: 51.5074,
    longitude: -0.1278,
    website_url: 'https://example.com/ljcc',
    facebook_url: null,
    youtube_url: null,
    education_activity: 'unknown',
    activity_level: 'medium',
    opportunity_score: 5,
    status: 'Follow Up',
    next_action: 'Connect with programming director',
    notes: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 13,
    name: 'Shaarei Tzedek Minneapolis',
    type: 'Synagogue',
    city: 'Minneapolis',
    state_province: 'MN',
    country: 'USA',
    latitude: 44.9778,
    longitude: -93.2650,
    website_url: null,
    facebook_url: null,
    youtube_url: null,
    education_activity: 'no',
    activity_level: 'none',
    opportunity_score: 6,
    status: 'Needs Action',
    next_action: 'Assess educational capacity',
    notes: 'Medium-sized congregation. No education program found.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 14,
    name: 'Brooklyn Hebrew School Network',
    type: 'School',
    city: 'Brooklyn',
    state_province: 'NY',
    country: 'USA',
    latitude: 40.6782,
    longitude: -73.9442,
    website_url: 'https://example.com/bhsn',
    facebook_url: null,
    youtube_url: 'https://youtube.com/bhsn',
    education_activity: 'yes',
    activity_level: 'high',
    opportunity_score: 9,
    status: 'Active',
    next_action: null,
    notes: 'Network of 5 schools. Key strategic partner.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 15,
    name: 'Phoenix Jewish Education Gap',
    type: 'Opportunity',
    city: 'Phoenix',
    state_province: 'AZ',
    country: 'USA',
    latitude: 33.4484,
    longitude: -112.0740,
    website_url: null,
    facebook_url: null,
    youtube_url: null,
    education_activity: 'no',
    activity_level: 'none',
    opportunity_score: 7,
    status: 'Prospect',
    next_action: 'Map local institutions',
    notes: 'Underserved market. High opportunity for expansion.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];
